name: Publish Docker container image to Docker Hub

on:
  push:
    branches:
      - next
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract tags and labels
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ github.repository }}

      - name: Build container image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile
          tags: local:test
          labels: ${{ steps.meta.outputs.labels }}
          load: true

      - name: Test container image
        run: docker run --rm -v $PWD:/workdir local:test "*.md"

      - name: Push container image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/arm64,linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
